import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
      icons: {
        // 💡 기본 파비콘 및 브라우저 탭 아이콘
        icon: '/aurora_pay_icon.png',
    
        // 💡 바로가기(shortcut) 아이콘
        shortcut: '/aurora_pay_icon.png',
    
        // 💡 Apple 기기 홈 화면 아이콘 (코인베이스 월렛 등 모바일 앱에서 가장 중요!)
        apple: '/aurora_pay_icon.png',
    
        // 💡 기타 아이콘 (예: 안드로이드 크롬 등)
        other: {
          rel: 'android-chrome-icon',
          url: '/aurora_pay_icon.png',
        },
      },
    other: {
      "fc:frame": JSON.stringify({
        version: "next",
        imageUrl: '/aurora_pay_icon.png',
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            type: "launch_frame",
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            url: URL,
            splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
            splashBackgroundColor:
              process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
          },
        },
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>Aurora Pay</title>
      <meta
        name="description"
        content="Aurora Pay leads the evolution of digital payments. We provide a simplified and frictionless solution for stablecoin-to-fiat conversion."
      />
    </head>
    <body className="bg-background">
      <Providers>{children}</Providers>
    </body>
  </html>
  );
}
